<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Travel Inquiry</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #238636; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 8px 8px; }
        .inquiry-details { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .detail-row { margin: 10px 0; }
        .label { font-weight: bold; color: #238636; }
        .footer { text-align: center; margin-top: 30px; color: #666; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🌟 New Travel Inquiry Received!</h1>
        </div>
        
        <div class="content">
            <p>Hello Admin,</p>
            
            <p>A new travel inquiry has been submitted through the North Trippers website. Here are the details:</p>
            
            <div class="inquiry-details">
                <h3>📋 Inquiry Details</h3>
                
                <div class="detail-row">
                    <span class="label">🏞️ Destination:</span> {{ $inquiry->destination }}
                </div>
                
                @if($inquiry->travel_date)
                <div class="detail-row">
                    <span class="label">📅 Travel Date:</span> {{ \Carbon\Carbon::parse($inquiry->travel_date)->format('F j, Y') }}
                </div>
                @endif
                
                @if($inquiry->travelers)
                <div class="detail-row">
                    <span class="label">👥 Number of Travelers:</span> {{ $inquiry->travelers }}
                </div>
                @endif
                
                @if($inquiry->name)
                <div class="detail-row">
                    <span class="label">👤 Name:</span> {{ $inquiry->name }}
                </div>
                @endif
                
                @if($inquiry->email)
                <div class="detail-row">
                    <span class="label">📧 Email:</span> {{ $inquiry->email }}
                </div>
                @endif
                
                @if($inquiry->phone)
                <div class="detail-row">
                    <span class="label">📞 Phone:</span> {{ $inquiry->phone }}
                </div>
                @endif
                
                <div class="detail-row">
                    <span class="label">⏰ Submitted At:</span> {{ \Carbon\Carbon::parse($inquiry->created_at)->format('F j, Y \a\t g:i A') }}
                </div>
            </div>
            
            <p><strong>Action Required:</strong> Please follow up with this inquiry as soon as possible to provide the best customer service.</p>
            
            <div class="footer">
                <p>This email was automatically generated by the North Trippers inquiry system.</p>
                <p>© {{ date('Y') }} North Trippers. All rights reserved.</p>
            </div>
        </div>
    </div>
</body>
</html>